version: '3.8'

services:
  # ShardXノード
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "54868:54868"
    expose:
      - "54868"
    environment:
      - PORT=54868
      - NODE_ID=node1
      - LOG_LEVEL=info
      - INITIAL_SHARDS=256
      - DATA_DIR=/app/data
    restart: unless-stopped
    networks:
      - shardx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:54868/info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - shardx-data:/app/data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  # Webインターフェース
  web:
    image: nginx:alpine
    ports:
      - "54867:80"
    expose:
      - "80"
    volumes:
      - ./web/dist:/usr/share/nginx/html
    depends_on:
      node:
        condition: service_healthy
    environment:
      - API_URL=http://node:54868
    networks:
      - shardx-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
          
  # Redis（クロスシャード通信用 - オプション）
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - shardx-network

volumes:
  shardx-data:
    driver: local
  redis-data:
    driver: local

networks:
  shardx-network:
    driver: bridge