name: shardx-debug

services:
  # ShardXノード
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "54868:54868"
    environment:
      - PORT=54868
      - NODE_ID=debug_node
      - LOG_LEVEL=debug
      - RUST_LOG=debug
      - INITIAL_SHARDS=256
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:54868/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Webインターフェース
  web:
    image: nginx:alpine
    ports:
      - "54867:80"
    volumes:
      - ./web/dist:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    restart: unless-stopped

  # デバッグ用Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # デバッグ用ツール
  debug-tools:
    image: alpine:latest
    volumes:
      - ./:/app
    depends_on:
      - node
    command: >
      sh -c "
        apk add --no-cache curl jq htop && 
        echo 'Debug tools container started' && 
        tail -f /dev/null
      "
    restart: unless-stopped