# fly.toml - Fly.io設定ファイル
app = "shardx"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "immediate"

[env]
  NODE_ID = "fly_node"
  RUST_LOG = "info"
  INITIAL_SHARDS = "64"
  DATA_DIR = "/app/data"
  REDIS_ENABLED = "true"
  WEB_ENABLED = "true"
  PORT = "54868"
  P2P_PORT = "54867"

[http]
  internal_port = 54868
  force_https = true

[[services]]
  http_checks = []
  internal_port = 54868
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[services]]
  http_checks = []
  internal_port = 54867
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 54867
    handlers = ["tcp"]

[mounts]
  source = "shardx_data"
  destination = "/app/data"

[metrics]
  port = 54868
  path = "/metrics"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1