# fly.toml - Fly.io設定ファイル
app = "shardx"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"
  builder = "dockerfile"

[env]
  NODE_ID = "fly_node"
  RUST_LOG = "info"
  INITIAL_SHARDS = "64"
  DATA_DIR = "/app/data"
  REDIS_ENABLED = "true"
  WEB_ENABLED = "true"
  PORT = "54868"
  P2P_PORT = "54867"

[http_service]
  internal_port = 54868
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[services]
  [services.web]
    protocol = "tcp"
    internal_port = 54868
    processes = ["app"]

    [[services.web.ports]]
      port = 80
      handlers = ["http"]
      force_https = true

    [[services.web.ports]]
      port = 443
      handlers = ["tls", "http"]

    [services.web.concurrency]
      type = "connections"
      hard_limit = 1000
      soft_limit = 500

  [services.p2p]
    protocol = "tcp"
    internal_port = 54867
    processes = ["app"]

    [[services.p2p.ports]]
      port = 54867
      handlers = ["tcp"]

[mounts]
  source = "shardx_data"
  destination = "/app/data"

[metrics]
  port = 9091
  path = "/metrics"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1