services:
  # ShardXノード（軽量設定）
  - type: web
    name: shardx-node
    env: docker
    dockerfilePath: ./Dockerfile.simple
    dockerContext: .
    plan: free # 無料プラン
    healthCheckPath: /info
    envVars:
      - key: PORT
        value: 54868
      - key: NODE_ID
        value: render_node
      - key: RUST_LOG
        value: info
      - key: INITIAL_SHARDS
        value: "10" # シャード数を減らして軽量化
      - key: DATA_DIR
        value: /tmp/shardx-data # 一時ディレクトリを使用

  # Webインターフェース（静的サイト）
  - type: static_site # 静的サイト用のタイプ
    name: shardx-web
    buildCommand: echo "Static site ready" # ビルド不要の軽量設定
    publishDir: ./web/dist # 公開ディレクトリ
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - source: /api/*
        destination: https://shardx-node.onrender.com/*
      - source: /*
        destination: /index.html
    envVars:
      - key: API_URL
        value: https://shardx-node.onrender.com