services:
  # ShardXノード（軽量設定）
  - type: web
    name: shardx-node
    env: docker
    dockerfilePath: ./Dockerfile.simple
    dockerContext: .
    plan: free # 無料プラン
    healthCheckPath: /info
    envVars:
      - key: PORT
        value: 54868
      - key: NODE_ID
        value: render_node
      - key: RUST_LOG
        value: info
      - key: INITIAL_SHARDS
        value: "10" # シャード数を減らして軽量化
    disk:
      name: shardx-data
      mountPath: /app/data
      sizeGB: 1 # 無料プランでは小さいサイズに制限

  # Webインターフェース（静的サイト）
  - type: web
    name: shardx-web
    env: static
    buildCommand: echo "Static site ready" # ビルド不要の軽量設定
    staticPublishPath: ./web/dist
    plan: free # 無料プラン
    routes:
      - type: rewrite
        source: /api/*
        destination: https://shardx-node.onrender.com/*
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: API_URL
        value: https://shardx-node.onrender.com

# 無料プランではRedisとデータベースは使用しない