services:
  # ShardXノード（軽量設定）
  - type: web
    name: shardx-node
    env: docker
    dockerfilePath: ./Dockerfile.simple
    dockerContext: .
    plan: free # 無料プラン
    healthCheckPath: /info
    envVars:
      - key: PORT
        value: 54868
      - key: NODE_ID
        value: render_node
      - key: RUST_LOG
        value: info
      - key: INITIAL_SHARDS
        value: "10" # シャード数を減らして軽量化
      - key: DATA_DIR
        value: /tmp/shardx-data # 一時ディレクトリを使用

  # Webインターフェース（Pythonサーバー）
  - type: web
    name: shardx-web
    env: python
    buildCommand: cd web && pip install -r requirements.txt
    startCommand: cd web && python server.py
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    envVars:
      - key: PORT
        value: 52153
      - key: API_URL
        value: https://shardx-node.onrender.com