pub mod did;
pub mod verifiable_credential;
pub mod verifiable_presentation;
pub mod resolver;
pub mod registry;
pub mod document;
pub mod method;
pub mod service;
pub mod authentication;
pub mod verification;
pub mod revocation;
pub mod key_management;
pub mod storage;
pub mod schema;
pub mod issuer;
pub mod holder;
pub mod verifier;
pub mod trust_framework;
pub mod governance;

pub use did::{DID, DIDMethod, DIDResolver, DIDDocument, DIDService, DIDAuthentication, DIDVerificationMethod};
pub use verifiable_credential::{VerifiableCredential, CredentialSubject, CredentialStatus, CredentialSchema, CredentialEvidence, CredentialProof};
pub use verifiable_presentation::{VerifiablePresentation, PresentationProof};
pub use resolver::{Resolver, ResolverOptions, ResolverResult, ResolverMetadata};
pub use registry::{Registry, RegistryEntry, RegistryMetadata, RegistryOptions};
pub use document::{Document, DocumentMetadata, DocumentOptions};
pub use method::{Method, MethodMetadata, MethodOptions};
pub use service::{Service, ServiceEndpoint, ServiceMetadata, ServiceOptions};
pub use authentication::{Authentication, AuthenticationMethod, AuthenticationMetadata, AuthenticationOptions};
pub use verification::{Verification, VerificationMethod, VerificationMetadata, VerificationOptions};
pub use revocation::{Revocation, RevocationList, RevocationStatus, RevocationMetadata, RevocationOptions};
pub use key_management::{KeyManager, KeyPair, KeyType, KeyAlgorithm, KeyFormat, KeyMetadata, KeyOptions};
pub use storage::{IdentityStorage, StorageOptions, StorageMetadata};
pub use schema::{Schema, SchemaValidator, SchemaMetadata, SchemaOptions};
pub use issuer::{Issuer, IssuerMetadata, IssuerOptions};
pub use holder::{Holder, HolderMetadata, HolderOptions};
pub use verifier::{Verifier, VerifierMetadata, VerifierOptions};
pub use trust_framework::{TrustFramework, TrustAnchor, TrustMetadata, TrustOptions};
pub use governance::{Governance, GovernancePolicy, GovernanceMetadata, GovernanceOptions};