apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - storage.yaml

namespace: shardx

commonLabels:
  app: shardx

images:
  - name: enablerdao/shardx
    newTag: latest

configMapGenerator:
  - name: shardx-config
    literals:
      - LOG_LEVEL=info
      - INITIAL_SHARDS=256