apiVersion: v1
kind: Service
metadata:
  name: shardx-node
  labels:
    app: shardx
    component: node
spec:
  selector:
    app: shardx
    component: node
  ports:
  - port: 54868
    targetPort: 54868
    name: api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: shardx-web
  labels:
    app: shardx
    component: web
spec:
  selector:
    app: shardx
    component: web
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: shardx-redis
  labels:
    app: shardx
    component: redis
spec:
  selector:
    app: shardx
    component: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shardx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: shardx.example.com  # 実際のドメインに変更してください
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shardx-web
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: shardx-node
            port:
              number: 54868