apiVersion: v1
kind: ConfigMap
metadata:
  name: shardx-config
  namespace: shardx
data:
  # 共通設定
  LOG_LEVEL: "info"
  DATA_DIR: "/app/data"
  
  # メモリ最適化設定
  MEMORY_LIMIT: "2G"
  GC_INTERVAL: "60"
  WARNING_THRESHOLD: "70"
  CRITICAL_THRESHOLD: "85"
  AUTO_OPTIMIZE: "true"
  
  # ストレージ最適化設定
  COMPACTION_THRESHOLD: "100M"
  COMPACTION_INTERVAL: "3600"
  MAX_FILE_SIZE: "1G"
  AUTO_COMPACT: "true"
  COMPRESSION_LEVEL: "6"
  
  # クロスシャード最適化設定
  BATCH_SIZE: "50"
  BATCH_INTERVAL_MS: "100"
  ROUTING_UPDATE_INTERVAL: "60"
  MAX_PARALLEL_EXECUTIONS: "10"
  
  # シャード設定
  SHARD_COUNT: "5"
  
  # ポート設定
  API_PORT: "8080"
  P2P_PORT: "9000"
  RPC_PORT: "8545"
  
  # Prometheus設定
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'shardx-nodes'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - shardx
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: shardx-.*
            action: keep
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: instance
  
  # Nginx設定
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
        
        location /api/ {
            proxy_pass http://shardx-main-node:8080/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }