name: Branch Protection

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup branch protection
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure branch protection
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const branch = 'main';
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: branch,
                required_status_checks: {
                  strict: true,
                  contexts: ['test', 'build']
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false,
                  required_approving_review_count: 1
                },
                restrictions: null
              });
              console.log('Branch protection rules updated successfully');
            } catch (error) {
              console.log('Error updating branch protection rules:', error);
              // Continue workflow even if branch protection update fails
              // This prevents CI/CD pipeline from failing due to permission issues
            }