name: Static Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev build-essential clang libclang-dev llvm-dev
          sudo apt-get install -y libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
      
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Set LIBCLANG_PATH
        run: |
          find /usr -name libclang.so* | head -n 1 | xargs dirname > /tmp/libclang_path
          echo "LIBCLANG_PATH=$(cat /tmp/libclang_path)" >> $GITHUB_ENV
          echo "Found libclang at: $LIBCLANG_PATH"
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-stable"
      
      - name: Run Clippy
        run: |
          if [ -f ./tools/static_analysis/run_analysis.sh ]; then
            chmod +x ./tools/static_analysis/run_analysis.sh
            ./tools/static_analysis/run_analysis.sh --clippy
          else
            echo "Static analysis script not found, running clippy directly"
            cargo clippy --no-default-features --features=snow -- -D warnings
          fi
      
      - name: Run rustfmt
        run: |
          if [ -f ./tools/static_analysis/run_analysis.sh ]; then
            ./tools/static_analysis/run_analysis.sh --fmt
          else
            echo "Static analysis script not found, running rustfmt directly"
            cargo fmt --all -- --check
          fi
      
      - name: Upload analysis report
        uses: actions/upload-artifact@v4
        with:
          name: static-analysis-report
          path: |
            target/static_analysis/static_analysis_report.md
            target/clippy-*.log
          if-no-files-found: ignore