name: Static Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev clang libclang-dev llvm-dev
          sudo apt-get install -y libgflags-dev libsnappy-dev zlib1g-dev liblz4-dev libzstd-dev libbz2-dev
          sudo apt-get install -y cmake ninja-build
      
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      
      - name: Set LIBCLANG_PATH
        run: |
          # 直接パスを指定する方法に変更
          echo "LIBCLANG_PATH=/usr/lib/llvm-14/lib" >> $GITHUB_ENV
          echo "Using libclang at: /usr/lib/llvm-14/lib"
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-stable"
      
      - name: Run Clippy
        run: |
          if [ -f ./tools/static_analysis/run_analysis.sh ]; then
            chmod +x ./tools/static_analysis/run_analysis.sh
            ./tools/static_analysis/run_analysis.sh --clippy || true
          else
            # 初回実行時はエラーを無視して依存関係をビルドする
            cargo clippy --no-default-features --features=snow || true
            # 2回目の実行でエラーをチェック（警告はエラーとして扱わない）
            cargo clippy --no-default-features --features=snow
          fi
      
      - name: Run rustfmt
        run: |
          if [ -f ./tools/static_analysis/run_analysis.sh ]; then
            chmod +x ./tools/static_analysis/run_analysis.sh
            ./tools/static_analysis/run_analysis.sh --fmt || true
          else
            cargo fmt --all -- --check
          fi
      
      - name: Upload analysis report
        uses: actions/upload-artifact@v4
        with:
          name: static-analysis-report
          path: |
            target/static_analysis/static_analysis_report.md
            target/clippy-*.log
          if-no-files-found: ignore